### PR TITLE
Add `async` method to exports

### PR DESCRIPTION
**Pull request by i-am-tom**
Hello!

In answer to #1, I've added the other method and updated the tests :) I also removed the `opts` param as it wasn't being used. The `then-request` package comes from a mention in the `sync-request` package's README.

I hope you like it!

### CODE REVIEW

**Comment by i-am-tom** [comment]
Huh, there's an issue with Semistandard... looking into it now.

EDIT: fixed by bumping the version to 7.0.2. Not sure what the issue is, but it's gone now!

(Thanks, https://github.com/nebez/gulp-semistandard/issues/3)

**Comment by i-am-tom** [comment]
All done! The tests failed on the last build because the requests aren't authenticated. They should pass if you manually restart the build (which I can't do without the permissions!)

**Comment by icyflame** [comment]
@i-am-tom Hey, thanks a lot for this patch! :) Your choice of module for this is perfect.

A few things that I would like in this patch:
1. Please keep the old API as is, I want the default version of this module to be the `sync` version. So, simply do `module.exports = exports.sync = function() { ... }`
2. Please add an `err` as the first parameter of the callback function (per Node convention :smile_cat: )
3. Update the tests to have three tests for `ghGistOwner(...)`, `ghGistOwner.sync(...)`, and `ghGistOwner.async(...)`
4. Update the README to include the new `async` function. Specifically the [Usage](https://github.com/icyflame/gh-gist-owner#usage) and the [API](https://github.com/icyflame/gh-gist-owner#api) sections.

**Comment by i-am-tom** [comment]
Cool - I'll get to it!

**Comment by i-am-tom** [comment]
All done! A couple of things I should probably note:
- Having a default export _and_ other exports is messy - you have to make the others properties of whatever the default is, which isn't really great. Most ES6 module transpilers use `exports.default` to represent the default, so that's maybe something to consider.
- Node convention would probably be to return a promise - it would also cut down on the boilerplate introduced in the last commit 😛 

Still, these are things for another day! By pure luck, Travis' traffic is low enough that the tests passed :D

**Comment by icyflame** [comment]
@i-am-tom Noted! Indeed, another day. I might actually look into the promise API and try to implement it here some day!

Thanks a lot for this patch :smile:

**Comment by i-am-tom** [comment]
No problem at all! It's actually pretty straightforward - just change the `done` to a `then` that does the `return res.owner.login` and then return it :)

**Pull request merged**
